<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="precmed">
<title>Examples for survival outcome  
Vignette 3 of 5
 • precmed</title>
<script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.1.3/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.1.3/bootstrap.bundle.min.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- bootstrap-toc --><script src="https://cdn.rawgit.com/afeld/bootstrap-toc/v1.0.1/dist/bootstrap-toc.min.js"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- search --><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Examples for survival outcome  
Vignette 3 of 5
">
<meta property="og:description" content="precmed">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>
    

    <nav class="navbar fixed-top navbar-light navbar-expand-lg bg-light"><div class="container">
    
    <a class="navbar-brand me-2" href="../index.html">precmed</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">1.0.0.9000</small>

    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item">
  <a class="nav-link" href="../reference/index.html">Reference</a>
</li>
<li class="active nav-item dropdown">
  <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" id="dropdown-articles">Articles</a>
  <div class="dropdown-menu" aria-labelledby="dropdown-articles">
    <a class="dropdown-item" href="../articles/General-introduction.html">A general introduction  
Vignette 1 of 5
</a>
    <a class="dropdown-item" href="../articles/Count-examples.html">Examples for count outcome  
Vignette 2 of 5
</a>
    <a class="dropdown-item" href="../articles/Survival-examples.html">Examples for survival outcome  
Vignette 3 of 5
</a>
    <a class="dropdown-item" href="../articles/Additional-examples.html">Additional examples  
Vignette 4 of 5
</a>
    <a class="dropdown-item" href="../articles/Theoretical-details.html">Theoretical details  
Vignette 5 of 5
</a>
  </div>
</li>
<li class="nav-item">
  <a class="nav-link" href="../news/index.html">Changelog</a>
</li>
      </ul>
<form class="form-inline my-2 my-lg-0" role="search">
        <input type="search" class="form-control me-sm-2" aria-label="Toggle navigation" name="search-input" data-search-index="../search.json" id="search-input" placeholder="Search for" autocomplete="off">
</form>

      <ul class="navbar-nav"></ul>
</div>

    
  </div>
</nav><div class="container template-article">




<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="" class="logo" alt=""><h1>Examples for survival outcome  
Vignette 3 of 5
</h1>
            
            <h4 data-toc-skip class="date">October 21, 2022</h4>
      
      
      <div class="d-none name"><code>Survival-examples.Rmd</code></div>
    </div>

    
    
<!-- badges: start -->
<p><a href="https://cran.r-project.org/package=precmed" class="external-link"><img src="https://www.r-pkg.org/badges/version/precmed" alt="CRAN_Status_Badge"></a> <a href="https://cran.r-project.org/package=precmed" class="external-link"><img src="https://cranlogs.r-pkg.org/badges/last-month/precmed" alt="metacran downloads"></a> <!-- badges: end --></p>
<img src="sticker4.jpg" alt="logo" style="position:absolute; top:0; right:10px; padding:0px;" width="300px" heigth="300px"><h1>
precmed: Precision Medicine in R
</h1>
<p>A doubly robust precision medicine approach to estimate and validate
conditional average treatment effects</p>
<div class="section level2">
<h2 id="load-required-packages">Load required packages<a class="anchor" aria-label="anchor" href="#load-required-packages"></a>
</h2>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va">precmed</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org" class="external-link">dplyr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org" class="external-link">ggplot2</a></span><span class="op">)</span></span></code></pre></div>
</div>
<div class="section level2">
<h2 id="examples-with-survival-outcomes">Examples with survival outcomes<a class="anchor" aria-label="anchor" href="#examples-with-survival-outcomes"></a>
</h2>
<p>We use the following simulated data to demonstrate the
<code>precmed</code> functions for survival outcomes. The data set
<code>survivalExample</code> was simulated based on real-world claims
data in multiple sclerosis and has 4,000 observations and 9
variables.</p>
<ul>
<li><p>We will use <code>y</code> as the survival outcome, which is the
number of days until the first relapse or censoring, whichever comes
first.</p></li>
<li><p>We will use <code>d</code> as the event indicator, where <span class="math inline">\(1\)</span> represents an event and <span class="math inline">\(0\)</span> represents censoring. The censoring
rate is about 84%.</p></li>
<li><p>We will use <code>trt</code> as the treatment variable, which has
2 drugs (drug0 and drug1).</p></li>
<li><p>The rest of the variables are baseline patient characteristics.
Variable <code>age</code> is centered at 48 years old. The medical costs
in the year prior to treatment initiation <code>previous_cost</code> is
centered at 14,362 USD and scaled with standard deviation 24,266
USD.</p></li>
</ul>
<pre><code><span><span class="co">## 'data.frame':    4000 obs. of  9 variables:</span></span>
<span><span class="co">##  $ age                     : num [1:4000, 1] -26.83 -2.83 -12.83 -20.83 6.17 ...</span></span>
<span><span class="co">##   ..- attr(*, "scaled:center")= num 45.8</span></span>
<span><span class="co">##  $ female                  : int  1 1 1 0 0 1 1 1 1 1 ...</span></span>
<span><span class="co">##  $ previous_treatment      : Factor w/ 3 levels "drugA","drugB",..: 3 1 3 1 3 1 3 3 3 1 ...</span></span>
<span><span class="co">##  $ previous_cost           : num [1:4000, 1] -0.341 -0.239 -0.171 -0.392 -0.518 ...</span></span>
<span><span class="co">##   ..- attr(*, "scaled:center")= num 14362</span></span>
<span><span class="co">##   ..- attr(*, "scaled:scale")= num 24266</span></span>
<span><span class="co">##  $ previous_number_symptoms: Factor w/ 3 levels "0","1","&gt;=2": 2 2 2 3 3 2 3 2 2 2 ...</span></span>
<span><span class="co">##  $ previous_number_relapses: int  0 1 2 0 1 0 0 2 0 0 ...</span></span>
<span><span class="co">##  $ trt                     : Factor w/ 2 levels "drug0","drug1": 1 1 1 1 2 1 2 2 2 2 ...</span></span>
<span><span class="co">##  $ y                       : num  102.1 51.3 104.9 61.5 35.6 ...</span></span>
<span><span class="co">##  $ d                       : num  0 0 0 0 0 0 0 0 0 1 ...</span></span></code></pre>
<div class="section level3">
<h3 id="internal-validation-via-catecv">Internal validation via <code>catecv()</code><a class="anchor" aria-label="anchor" href="#internal-validation-via-catecv"></a>
</h3>
<p>We first run the internal validation to compare 5 scoring methods.
This is done with the function <code><a href="../reference/catecv.html">catecv()</a></code>. This first step
gives results in the form of a “precmed” object which will be used in
the next steps to compare the performance of the scoring methods.</p>
<p>The mandatory arguments in <code><a href="../reference/catecv.html">catecv()</a></code> are
<code>response</code>, <code>data</code>, <code>score.method</code>,
<code>cate.model</code>, and <code>ps.model</code>. They must be
specified by the user.</p>
<ul>
<li><p>The <code>response</code> argument specifies the type of outcome
in the data. For survival outcomes, <code>response</code> = “survival”.
This informs the function of the necessary arguments and methods to
use.</p></li>
<li><p>The argument <code>data</code> indicates the data frame in which
the outcome, treatment and covariates specified in either
<code>cate.model</code> or <code>ps.model</code> should be
fetched.</p></li>
<li>
<p>The <code>score.method</code> argument specifies the precision
medicine (PM) methods to be used to calculate the CATE scores. There are
a total of 5 scoring methods implemented:</p>
<ul>
<li><p><code>poisson</code> fits a Poisson model separately by treatment
group.</p></li>
<li><p><code>boosting</code> uses gradient boosted regression models
(GBM) separately by treatment group.</p></li>
<li><p><code>randomForest</code> fits a random forest model by treatment
group.</p></li>
<li><p><code>twoReg</code> implements the doubly robust two regressions
estimator in <span class="citation">@yadlowsky2020estimation</span>.</p></li>
<li><p><code>contrastReg</code> implements the doubly robust contrast
regression estimator from <span class="citation">@yadlowsky2020estimation</span>.</p></li>
</ul>
</li>
</ul>
<p>For this toy example we selected <code>randomForest</code> and
<code>contrastReg</code> to limit run time.</p>
<ul>
<li><p>The argument <code>cate.model</code> specifies the CATE model as
a formula, with the survival object from the <code>survival</code>
package, <code>Surv(y, d)</code>, supplied on the left-hand side and the
explanatory covariates supplied on the right-hand side. In the example
below, we chose to specify to CATE as a linear combination of the
following covariates: age, sex, medical costs in the year prior to
treatment initiation, and number of relapses in the year prior to
treatment initiation. Non-linear or interaction terms could also be
included. Note that the treatment variable is not supplied in
<code>cate.model</code> since this is an outcome model.</p></li>
<li><p>The <code>ps.model</code> argument specifies the PS model as a
formula, with the treatment variable <code>trt</code> on the left-hand
side and the covariates (age and previous treatment in this example) on
the right-hand side. The variable <code>trt</code> must be supplied as a
numeric variable taking only 2 values, “1” for active treatment and “0”
for control or comparator. If it is not the case, <code><a href="../reference/catecv.html">catecv()</a></code>
will stop with error if <code>trt</code> takes more than 2 distinct
values or will automatically transform <code>trt</code> into a numeric
variable. In this example, <code>trt</code> (a factor variable taking
values “drug0” and “drug1”) was transformed and a warning message was
left to the user (see output below):
<code>Variable trt was recoded to 0/1 with drug0-&gt;0 and drug1-&gt;1</code>.
If the data are from a RCT, it suffices to specify <code>ps.model</code>
= trt ~ 1. Note that the PS model is only used in the estimation of the
2 doubly robust methods (two and contrast regressions).</p></li>
</ul>
<p>We also specified the following non-mandatory arguments to fit with
the data and problem at hand: <code>initial.predictor.method</code>,
<code>ipcw.model</code>, <code>verbose</code>,
<code>followup.time</code>, <code>tau0</code>, <code>higher.y</code>,
<code>cv.n</code>, <code>surv.min</code>, <code>seed</code>, and
<code>plot.gbmperf</code>.</p>
<ul>
<li><p><code>initial.predictor.method</code> specifies how predictions
of the outcome are estimated in two regressions and contrast regression.
Flexible models can be used such as GBM (“boosting”), random forests
(“randomForest”) or logistic regression (“logistic”). We chose
“logistic” because it is relatively faster than boosting methods and
random forest.</p></li>
<li><p>The <code>ipcw.model</code> argument specifies the inverse
proability of censoring weighting (IPCW) model as a formula, with the
left-hand side empty and the covariates on the right-hand side. The IPCW
model calculates the probability of being censored as weights to be
included in the PM methods in order to correct for right censoring. In
the example below, we chose to specify IPCW model as a linear
combination of age, medical costs in the year prior to treatment
initiation, and previous treatment. This argument can be left default as
<code>NULL</code> if the user wants to use the same covariates provided
in the outcome model <code>cate.model</code> plus the treatment
variable.</p></li>
<li><p>We only output the progress of the CV procedure (but not the full
error messages and warnings) in the R console by setting
<code>verbose</code> = 1.</p></li>
<li><p><code>followup.time</code> specifies the maximum follow-up time
in the data. We set it default as <code>NULL</code>, which indicates
unknown potential censoring time.</p></li>
<li><p><code>tau0</code> is the truncation time for defining restricted
mean time lost (RMTL). We specified it as <code>NULL</code>, which
automatically sets the truncation time as the maximum survival time in
the data.</p></li>
<li><p><code>higher.y</code> was set to <code>TRUE</code> because
relapse is a negative event and longer time to first relapse is more
desirable in our example. Hence, we are telling the function that
subgroups of high responders to drug1 vs drug0 should have later onset
of the first relapse. In other situation, higher outcomes may be more
favorable for time to a positive event, e.g., time to discharge or time
to improved disability. It is important for this argument to match with
the nature of <code>y</code> outcome because it will affect how the
subgroups are defined by the CATE scores and the performance
metrics.</p></li>
<li><p>We performed 5 CV iterations by specifying <code>cv.n</code> = 5.
Typically, more CV iterations are desirable although associated with
longer computational times.</p></li>
<li><p><code>surv.min</code> truncates the censoring probability
estimated from the IPCW model with a lower limit to prevent extremely
small censoring probabilities. It is recommended to choose a small
positive value close to 0. We chose <code>0.025</code> in the example,
which corresponds to the default value.</p></li>
<li><p>We set a random seed <code>seed</code> = 999 to reproduce the
results.</p></li>
<li><p>We avoided generating the boosting performance plots by
specifying <code>plot.gbmperf</code> = FALSE.</p></li>
<li><p>When <code>verbose</code> = 1, progress messages are printed in
the R console but errors and warnings are not printed. The current CV
iteration is printed, followed by the steps of the CV procedure
(splitting the data, training the models, validating the models). A
timestamp and a progress bar are also displayed upon completion of a CV
iteration. If <code>contrastReg</code> was selected as one of the
methods in <code>score.method</code>, an additional line of output
message will indicate whether the algorithm has converged.</p></li>
</ul>
<p>There are many other non-mandatory arguments that
<code><a href="../reference/catecv.html">catecv()</a></code> can accept. Please see the <a href="Additional-examples.html">More Examples</a> section for more
examples and the Function description (<code><a href="../reference/catecvsurv.html">?catecvsurv</a></code>) for
details. If you run into errors or warnings with your data, it might be
helpful to go over the descriptions to see if you need to alter the
default values. In this toy example, we keep the default values of the
remaining arguments.</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">tau0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html" class="external-link">with</a></span><span class="op">(</span><span class="va">survivalExample</span>,</span>
<span>             <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html" class="external-link">min</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/quantile.html" class="external-link">quantile</a></span><span class="op">(</span><span class="va">y</span><span class="op">[</span><span class="va">trt</span> <span class="op">==</span> <span class="st">"drug1"</span><span class="op">]</span>, <span class="fl">0.95</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html" class="external-link">quantile</a></span><span class="op">(</span><span class="va">y</span><span class="op">[</span><span class="va">trt</span> <span class="op">==</span> <span class="st">"drug0"</span><span class="op">]</span>, <span class="fl">0.95</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">output_catecv</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/catecv.html">catecv</a></span><span class="op">(</span>response <span class="op">=</span> <span class="st">"survival"</span>,</span>
<span>                        data <span class="op">=</span> <span class="va">survivalExample</span>,</span>
<span>                        score.method <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"randomForest"</span>, <span class="st">"contrastReg"</span><span class="op">)</span>,</span>
<span>                        cate.model <span class="op">=</span> <span class="fu">survival</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html" class="external-link">Surv</a></span><span class="op">(</span><span class="va">y</span>, <span class="va">d</span><span class="op">)</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">female</span> <span class="op">+</span></span>
<span>                                     <span class="va">previous_cost</span> <span class="op">+</span> <span class="va">previous_number_relapses</span>,</span>
<span>                        ps.model <span class="op">=</span> <span class="va">trt</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">previous_treatment</span>,</span>
<span>                        initial.predictor.method <span class="op">=</span> <span class="st">"logistic"</span>,</span>
<span>                        ipcw.model <span class="op">=</span> <span class="cn">NULL</span>,</span>
<span>                        followup.time <span class="op">=</span> <span class="cn">NULL</span>,</span>
<span>                        tau0 <span class="op">=</span> <span class="va">tau0</span>,</span>
<span>                        higher.y <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>                        surv.min <span class="op">=</span> <span class="fl">0.025</span>,</span>
<span>                        prop.cutoff <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html" class="external-link">seq</a></span><span class="op">(</span><span class="fl">0.6</span>, <span class="fl">1</span>, length <span class="op">=</span> <span class="fl">5</span><span class="op">)</span>,</span>
<span>                        prop.multi <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">0.5</span>, <span class="fl">0.6</span>, <span class="fl">1</span><span class="op">)</span>,</span>
<span>                        cv.n <span class="op">=</span> <span class="fl">5</span>,</span>
<span>                        seed <span class="op">=</span> <span class="fl">999</span>,</span>
<span>                        plot.gbmperf <span class="op">=</span> <span class="cn">FALSE</span>,</span>
<span>                        verbose <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code></pre></div>
<pre><code><span><span class="co">## Warning in data.preproc.surv(fun = "crossv", cate.model = cate.model, ps.model = ps.model, : Variable trt was recoded to 0/1 with drug0-&gt;0 and drug1-&gt;1.</span></span></code></pre>
<pre><code>## 
  |                                                                            
  |                                                                      |   0%
## cv = 1 
##   splitting the data..
##   training..
##   validating..
##   Contrast regression converged.
##    Fri Oct 21 17:42:20 2022 
## 
  |                                                                            
  |==============                                                        |  20%
## cv = 2 
##   splitting the data..
##   training..
##   validating..
##   Contrast regression converged.
##    Fri Oct 21 17:42:40 2022 
## 
  |                                                                            
  |============================                                          |  40%
## cv = 3 
##   splitting the data..
##   training..
##   validating..
##   Contrast regression converged.
##    Fri Oct 21 17:43:01 2022 
## 
  |                                                                            
  |==========================================                            |  60%
## cv = 4 
##   splitting the data..
##   training..
##   validating..
##   Contrast regression converged.
##    Fri Oct 21 17:43:21 2022 
## 
  |                                                                            
  |========================================================              |  80%
## cv = 5 
##   splitting the data..
##   training..
##   validating..
##   Contrast regression converged.
##    Fri Oct 21 17:43:41 2022 
## 
  |                                                                            
  |======================================================================| 100%
## Total runtime : 1.71 mins</code></pre>
<p>The output of <code><a href="../reference/catecv.html">catecv()</a></code> is an object of class “precmed”
and here we named it <code>output_catecv</code>. It carries the relevant
information to use in the next step of the workflow which selects the
method (among those specified in the argument <code>score.method</code>)
capturing the highest level of treatment effect heterogeneity. The
output, which is described below, will be used in the functions
<code><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot()</a></code>, <code><a href="https://rdrr.io/r/graphics/boxplot.html" class="external-link">boxplot()</a></code> and <code><a href="../reference/abc.html">abc()</a></code>.</p>
<p>For each method specified in the argument <code>score.method</code>,
the following 4 groups of outputs are generated. We use the results from
<code>randomForest</code> as an example.</p>
<p><strong>1. ATEs in nested subgroups of high responders</strong></p>
<p>This output stores the ATEs - the ratio of RMTL between drug1 vs
drug0 in this example - in nested subgroups of patients of high
responders to drug 1 in the training
(<code>$ate.est.train.high.cv</code>) and validation
(<code>$ate.est.valid.high.cv</code>) sets across all CV iterations.
When <code>higher.y</code> = TRUE for survival outcomes, which is the
case in this example, lower CATE scores correspond to high responders to
drug1. When <code>higher.y</code> = FALSE for survival outcomes, higher
CATE scores correspond to high responders to drug1. Note that this is
different for count outcomes. The direction of CATE scores depends on
both <code>higher.y</code> and outcome type.</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">output_catecv</span><span class="op">$</span><span class="va">ate.randomForest</span><span class="op">$</span><span class="va">ate.est.train.high.cv</span></span></code></pre></div>
<pre><code><span><span class="co">##               cv1       cv2       cv3       cv4       cv5</span></span>
<span><span class="co">## prop0.6 0.4753124 0.4917526 0.4876323 0.5089093 0.5584117</span></span>
<span><span class="co">## prop0.7 0.6196242 0.6655303 0.6163124 0.6550763 0.6209161</span></span>
<span><span class="co">## prop0.8 0.7339630 0.7765458 0.7329931 0.7527532 0.7377974</span></span>
<span><span class="co">## prop0.9 0.8926423 0.9379673 0.8957898 0.9183219 0.8988051</span></span>
<span><span class="co">## prop1   1.0534514 1.1042633 1.0646558 1.0830122 1.0690691</span></span></code></pre>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">output_catecv</span><span class="op">$</span><span class="va">ate.randomForest</span><span class="op">$</span><span class="va">ate.est.valid.high.cv</span></span></code></pre></div>
<pre><code><span><span class="co">##               cv1       cv2       cv3       cv4       cv5</span></span>
<span><span class="co">## prop0.6 0.5081771 0.5282781 0.4875482 0.5879925 0.5056018</span></span>
<span><span class="co">## prop0.7 0.6209561 0.5433708 0.6375556 0.5917497 0.6089569</span></span>
<span><span class="co">## prop0.8 0.7970265 0.7169490 0.7944385 0.7349855 0.7500680</span></span>
<span><span class="co">## prop0.9 0.9830217 0.8543862 0.9462473 0.8868964 0.9248308</span></span>
<span><span class="co">## prop1   1.1465914 1.0194984 1.0968389 1.0526779 1.1027499</span></span></code></pre>
<p>The output is a matrix with columns corresponding to the CV
iterations, labeled from 1 to <code>cv.n</code>, and rows corresponding
to nested subgroups. The nested subgroups of patients are defined by the
argument <code>prop.cutoff</code>. Here, we use
<code>seq(0.6, 1, length = 5)</code> which defines nested subgroups with
the 60%, 70%, 80%, 90% and 100% lowest (highest if
<code>higher.y = FALSE</code>) CATE scores estimated by random forest.
The rows in the output are labeled to reflect the user-specified
proportions used to build the subgroups.</p>
<p>For example, in the training set and in the 4th CV iteration (4th
column labeled “cv4”), the subgroup defined with the 80% lowest CATE
scores (4th row labeled “prop0.8”) has an estimated RMTL ratio of 0.753.
In contrast, the subgroup defined with all patients (last row labeled
“prop1”) in the 4th CV iteration has an estimated RMTL ratio of 1.083.
<!-- This suggests that the CATE score estimated with random forests identifies high responders to drug 1 vs drug 0 because patients with the 50\% lowest estimated CATE score have a better (lower) RMTL ratio compared to all patients. If lower outcomes were preferable (as specified through the argument `higher.y`), subgroups would be defined with proportion of patients with *highest* estimated CATE score and *higher* RR would be better. --></p>
<p><strong>2. ATEs in nested subgroups of low responders</strong></p>
<p>This output stores the ATEs in nested subgroups of <em>low
responders</em> to drug1 in the training
(<code>$ate.est.train.low.cv</code>) and validation
(<code>$ate.est.valid.low.cv</code>) sets across all CV iterations. When
<code>higher.y</code> = TRUE for survival outcomes, higher CATE scores
correspond to low responders to drug1. When <code>higher.y</code> =
FALSE for survival outcomes, lower CATE scores correspond to low
responders to drug1. Again, this is different for count outcomes. The
direction of CATE scores depends on both <code>higher.y</code> and
outcome type.</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">output_catecv</span><span class="op">$</span><span class="va">ate.randomForest</span><span class="op">$</span><span class="va">ate.est.train.low.cv</span></span></code></pre></div>
<pre><code><span><span class="co">##               cv1       cv2      cv3       cv4       cv5</span></span>
<span><span class="co">## prop0.4  7.475048  6.763305  9.56552  7.574093  7.307854</span></span>
<span><span class="co">## prop0.3 38.211815 53.883349 96.68014 46.428207 46.385038</span></span>
<span><span class="co">## prop0.2       Inf        NA      Inf       Inf       Inf</span></span>
<span><span class="co">## prop0.1        NA        NA       NA        NA        NA</span></span></code></pre>
<p>The outputs are also matrices with columns corresponding to the CV
iterations and rows corresponding to nested subgroups.</p>
<p>The output for the low responders brings additional information to
the user. It gives the ATEs in the complement of each nested subgroup of
high responders. For example, the complement of the subgroup of high
responders defined as patients with the 60% lowest (highest if
<code>higher.y</code> = FALSE) estimated CATE scores is the subgroup of
low responders defined as patients with the 40% highest (lowest if
<code>higher.y</code> = TRUE) estimated CATE scores, labeled as
“prop0.4”. In the training set and in the first CV iterations, the
estimated RMTL ratio is 0.62 in the 60% high responders to drug 1 and
38.212 in the 40% low responders.</p>
<p>The 2 last rows have missing or infinite values and this can be due
to many reasons. We record all errors and warnings and keep them as an
element of the <code>cv</code> output. For example, we can use the
following code to check specific errors and warnings of the first CV
iteration (<code>$cv1</code>) using the random forest method
(<code>$randomForest</code>) when estimating the ATE in the training
sample in the low responder groups (<code>$est.train.low.cv</code>). It
looks like there was no event observation in the 10% subgroup, possibly
due to small sample size, which also relates to the convergence issue in
the warning. Additionally, the warning for the 20% subgroup
(<code>$warnings$'prop0.2'</code>) suggested that there was
non-convergence of the Cox procedure and that the corresponding
estimated ATE should be interpreted with caution.</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">output_catecv</span><span class="op">$</span><span class="va">`errors/warnings`</span><span class="op">$</span><span class="va">randomForest</span><span class="op">$</span><span class="va">est.train.low.cv</span><span class="op">$</span><span class="va">cv1</span></span></code></pre></div>
<pre><code><span><span class="co">## $errors</span></span>
<span><span class="co">## $errors$`prop 0.1`</span></span>
<span><span class="co">## [1] "Error in dimnames(means) &lt;- list(time, vname) : 'dimnames' applied to non-array"</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## </span></span>
<span><span class="co">## $warnings</span></span>
<span><span class="co">## $warnings$`prop 0.2`</span></span>
<span><span class="co">## [1] "Warning in coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter), coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter), coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter) : Ran out of iterations and did not converge"</span></span>
<span><span class="co">## [2] "Warning in coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter), coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter), coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter) : one or more coefficients may be infinite"  </span></span>
<span><span class="co">## [3] "Warning in coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter), coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter), coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter) : Ran out of iterations and did not converge"</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## $warnings$`prop 0.1`</span></span>
<span><span class="co">## [1] "Warning in coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter), coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter) : Ran out of iterations and did not converge"</span></span>
<span><span class="co">## [2] "Warning in coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter), coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter) : Ran out of iterations and did not converge"</span></span></code></pre>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">output_catecv</span><span class="op">$</span><span class="va">`errors/warnings`</span><span class="op">$</span><span class="va">randomForest</span><span class="op">$</span><span class="va">est.valid.low.cv</span><span class="op">$</span><span class="va">cv1</span></span></code></pre></div>
<pre><code><span><span class="co">## $errors</span></span>
<span><span class="co">## $errors$`prop 0.2`</span></span>
<span><span class="co">## [1] "Error in coxph(Surv(y, d) ~ x) : No (non-missing) observations"</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## $errors$`prop 0.1`</span></span>
<span><span class="co">## [1] "Error in coxph(Surv(y, d) ~ x) : No (non-missing) observations"</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## </span></span>
<span><span class="co">## $warnings</span></span>
<span><span class="co">## $warnings$`prop 0.4`</span></span>
<span><span class="co">## [1] "Warning in coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter) : Ran out of iterations and did not converge"</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## $warnings$`prop 0.3`</span></span>
<span><span class="co">## [1] "Warning in coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter), coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter) : Ran out of iterations and did not converge"                         </span></span>
<span><span class="co">## [2] "Warning in coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter), coxph.fit(X, Y, istrat, offset, init, control, weights = weights, method = method, rname, nocenter = nocenter) : Loglik converged before variable  4 ; coefficient may be infinite. "</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## $warnings$`prop 0.2`</span></span>
<span><span class="co">## [1] "Warning in max(event[who2]) : glm.fit: algorithm did not converge"            </span></span>
<span><span class="co">## [2] "Warning in max(event[who2]) : no non-missing arguments to max; returning -Inf"</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## $warnings$`prop 0.1`</span></span>
<span><span class="co">## [1] "Warning in max(event[who2]) : no non-missing arguments to max; returning -Inf"</span></span></code></pre>
<p><strong>3. ATEs in mutually exclusive multi-category
subgroups</strong></p>
<p>This output stores the ATEs in mutually exclusive multi-category
subgroups of patients in the training
(<code>$ate.est.train.group.cv</code>) and validation
(<code>$ate.est.valid.group.cv</code>) sets across all CV
iterations.</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">output_catecv</span><span class="op">$</span><span class="va">ate.randomForest</span><span class="op">$</span><span class="va">ate.est.train.group.cv</span></span></code></pre></div>
<pre><code><span><span class="co">##               cv1       cv2       cv3       cv4       cv5</span></span>
<span><span class="co">## prop0.5 3.4151485 3.5654842 3.7254944 3.6552745 3.6690400</span></span>
<span><span class="co">## prop0.6 1.2898656 1.0877241 1.0683353 1.1623681 0.9201879</span></span>
<span><span class="co">## prop1   0.2910105 0.4227029 0.2707232 0.2805186        NA</span></span></code></pre>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">output_catecv</span><span class="op">$</span><span class="va">ate.randomForest</span><span class="op">$</span><span class="va">ate.est.valid.group.cv</span></span></code></pre></div>
<pre><code><span><span class="co">##               cv1      cv2       cv3       cv4      cv5</span></span>
<span><span class="co">## prop0.5 4.7844569 3.439306 3.4420698 4.0713342 3.500151</span></span>
<span><span class="co">## prop0.6 0.8403764 1.197367 4.9331418 0.8511804 1.343130</span></span>
<span><span class="co">## prop1          NA       NA 0.3243074        NA       NA</span></span></code></pre>
<p>The output is a matrix with columns corresponding to the CV
iterations and rows corresponding to the mutually exclusive subgroups.
The previous 2 outputs only focus on binary subgroups (high or low
responders). Here, the mutually exclusive subgroups can be more than 2
and are defined by the argument <code>prop.multi</code>. We use
<code>c(0, 0.5, 0.6, 1)</code> which defines 3 subgroups of patients
with the 50% lowest, 10% middle and 40% highest estimated CATE scores
when <code>higher.y</code> = TRUE (as in this example), or with the 40%
highest, 10% middle and 50% lowest estimated CATE scores when
<code>higher.y</code> = FALSE. Taking the first column as an example,
the first CV iteration calculated 3.415 as the RMTL ratio for the
subgroup with the 50% lowest estimated CATE scores, 1.29 as the RMTL
ratio for the subgroup with the middle 10% estimated CATE scores, and
0.291 as the RMTL ratio for the subgroup with the 40% highest estimated
CATE scores. Use
<code>output_catecv$`errors/warnings`$randomForest$est.train.group.cv</code>
to learn more about the errors and warnings generated from these
outputs.</p>
</div>
<div class="section level3">
<h3 id="comparison-of-methods-with-abc">Comparison of methods with <code>abc()</code><a class="anchor" aria-label="anchor" href="#comparison-of-methods-with-abc"></a>
</h3>
<p>The ABC statistics is calculated by <code><a href="../reference/abc.html">abc()</a></code> for each
scoring method specified in <code><a href="../reference/catecv.html">catecv()</a></code> and for each of the
<code>cv.n</code> CV iterations using the output object
<code>output_catecv</code> from <code><a href="../reference/catecv.html">catecv()</a></code>. The ABC
corresponds to the area between the curve formed by the ATEs in
subgroups of high responders in the validation set (e.g.,
<code>output_catecv$ate.randomForest$ate.est.valid.cv</code> for random
forest) and the horizontal line representing the ATE in the validation
set. A higher ABC value means that the method captures more treatment
effect heterogeneity.</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">output_abc</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/abc.html">abc</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">output_catecv</span><span class="op">)</span></span>
<span><span class="va">output_abc</span></span></code></pre></div>
<pre><code><span><span class="co">##                    cv1       cv2       cv3       cv4       cv5</span></span>
<span><span class="co">## randomForest 0.1533033 0.1450798 0.1392829 0.1458115 0.1532764</span></span>
<span><span class="co">## contrastReg  0.1416306 0.1304287 0.1366230 0.1304199 0.1519283</span></span></code></pre>
<p>The output is a matrix with columns corresponding to the CV
iterations and rows corresponding to the scoring methods specified in
<code>score.method</code>. For example, random forest in CV iteration 1
has an ABC of 0.153, which is the highest in this CV iteration, meaning
that random forest offers the best performance in the first CV
iteration. The user can combine the ABC for each method across
iterations:</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">average_abc</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/apply.html" class="external-link">apply</a></span><span class="op">(</span><span class="va">output_abc</span>, <span class="fl">1</span>, <span class="va">mean</span><span class="op">)</span></span>
<span><span class="va">average_abc</span></span></code></pre></div>
<pre><code><span><span class="co">## randomForest  contrastReg </span></span>
<span><span class="co">##    0.1473508    0.1382061</span></span></code></pre>
<p>In this example, random forest also offers the best overall
performance because it has the highest average ABC, followed closely by
contrast regression.</p>
</div>
<div class="section level3">
<h3 id="visualization-of-the-validation-curves-with-plot">Visualization of the validation curves with <code>plot()</code><a class="anchor" aria-label="anchor" href="#visualization-of-the-validation-curves-with-plot"></a>
</h3>
<p>The ATEs of nested subgroups of high responders to drug1 (e.g.,
<code>output_catecv$ate.randomForest$ate.est.train.high.cv</code> and
<code>output_catecv$ate.randomForest$ate.est.valid.high.cv</code> for
random forest) can be visualized as a side-by-side line plot, with
training results on the left and validation results on the right. The
x-axis is determined by <code>prop.cutoff</code> and the y-axis is the
estimated ATEs averaged over <code>cv.n</code> CV iterations as
specified by <code>cv.i</code> = NULL (default). The estimated ATE is
expressed as a RMTL ratio of drug1 versus drug0 for our toy example. By
default, the function retrieves the name of the treatment variable
(<code>trt</code>) and the original labels (<code>drug0</code> and
<code>drug1</code>) to specify a meaningful y-axis label. Otherwise, it
is possible to customize the y-axis label via the <code>ylab</code>, for
example, by specifying <code>ylab</code> = “RMTL ratio of drug1 vs drug0
in each subgroup”.</p>
<p>Steeper slopes indicate more treatment effect heterogeneity between
drug1 and drug0. Because <code>higher.y</code> = TRUE in this example,
the slopes should be increasing from left (<code>prop.cutoff</code> =
0.6) to right (<code>prop.cutoff</code> = 1) if treatment effect
heterogeneity is present (see section <a href="Theoretical-details.html">Validation curves and the ABC
statistics</a> for illustration). The method that has the steepest slope
in the validation results would be selected because it captures the most
treatment effect heterogeneity while generalizing well to unseen
data.</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">output_catecv</span><span class="op">)</span></span></code></pre></div>
<p><img src="Survival-examples_files/figure-html/example_plot_lineplot1-1.png" width="1056"></p>
<p>For this toy example, the methods are performing well in the training
data as per the steep, increasing slopes on the left plot. Moreover, all
methods generalize well to the validation data, as indicated by the
monotonous increasing curves in the validation data (right plot). The
dashed gray line is the ATE in the entire data set, which is why all
lines merge to this reference line when subgroup size is 100% of the
data (<code>prop.cutoff</code> = 1). For more explanation on the
validation curves, see the function description.</p>
<p>The plot’s legend includes the ABC statistics in the validation set.
The user can choose to mute the ABC annotations by specifying
<code>show.abc</code> = FALSE.</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">output_catecv</span>, </span>
<span>     show.abc <span class="op">=</span> <span class="cn">FALSE</span>, </span>
<span>     ylab <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"RMTL ratio of drug1 vs drug0 in each subgroup"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p><img src="Survival-examples_files/figure-html/example_plot_lineplot1.1-1.png" width="700"></p>
<p>The user can choose to plot the validation curves of only 1 CV
iteration instead of the average of all CV iterations. In the following
example, we plot the validation curves of the second CV iteration by
specifying <code>cv.i</code> = 2 and in grayscale by specifying
<code>grayscale</code> = TRUE.</p>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">output_catecv</span>, </span>
<span>     cv.i <span class="op">=</span> <span class="fl">2</span>, </span>
<span>     grayscale <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>     ylab <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"RMTL ratio of drug1 vs drug0 in each subgroup"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p><img src="Survival-examples_files/figure-html/example_plot_lineplot2-1.png" width="700"></p>
<p>The user can also choose to use the median (instead of mean
[default]) of the ATEs across CV iterations by specifying the argument
<code>combine</code> = “median” in <code><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot()</a></code>.</p>
</div>
<div class="section level3">
<h3 id="visualization-of-the-ate-in-subgroups-with-boxplot">Visualization of the ATE in subgroups with
<code>boxplot()</code><a class="anchor" aria-label="anchor" href="#visualization-of-the-ate-in-subgroups-with-boxplot"></a>
</h3>
<p>The ATEs of multi-category subgroups that are mutually exclusive can
be visualized as box plots, with 1 box plot for each scoring method.
Only validation results are visualized here. The x-axis is determined by
<code>prop.multi</code> and the y-axis is the estimated ATEs in each
subgroup. We specify the <code>ylab</code> argument accordingly. The
subgroups correspond to each row of the
<code>ate.est.valid.group.cv</code> result in
<code>output_catecv</code>, so in this example the subgroups are patient
with the 50% lowest (0-50%), middle 10% (50-60%), and highest 40%
(60-100%) estimated CATE scores. Notice that the groups do not have to
be equally spaced in terms of percentiles. The box plot shows the
distribution of the ATEs over all <code>cv.n</code> CV iterations,
instead of a summary statistics like mean or median in
<code><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot()</a></code>.</p>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html" class="external-link">boxplot</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">output_catecv</span>,</span>
<span>        ylab <span class="op">=</span> <span class="st">"RMTL ratio of drug1 vs drug0 in each subgroup"</span><span class="op">)</span></span></code></pre></div>
<pre><code><span><span class="co">## Warning: Removed 4 rows containing non-finite values (stat_boxplot).</span></span></code></pre>
<p><img src="Survival-examples_files/figure-html/example_plot_boxplot-1.png" width="700"></p>
<p>For this toy example, we can see why random forest and contrast
regression methods have the 2 highest ABC and perform the best in the
validation curves in the previous sections. They both have the most
distinctive decreasing RMT ratio as we go from the subgroup with the 50%
lowest CATE scores (red) to subgroup with the 40% highest CATE scores
(blue). This implies that there is some evidence of heterogeneous
treatment effect and that the CATE scores estimated with random forest
or contrast regression can capture it. They also have relatively smaller
variation as the boxes are thinner. In comparison, the other 3 methods
also present this increasing trend in the box plots, but we observe a
larger variation in the RMTL ratio, especially with boosting. We can see
that the box plots correspond to the other 2 outputs, <code><a href="../reference/abc.html">abc()</a></code>
and <code><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot()</a></code>. Note that the y-axis can have different scales
for different scoring methods. <br><br></p>
<blockquote>
<p>So far we provided 3 different metrics to summarize, visualize, and
evaluate the <code><a href="../reference/catecv.html">catecv()</a></code> outputs. The user is encouraged to
choose their own way of data wrangling that fits to their particular
situation.</p>
</blockquote>
<p><br><br></p>
</div>
<div class="section level3">
<h3 id="estimation-of-the-cate-score-with-catefit">Estimation of the CATE score with <code>catefit()</code><a class="anchor" aria-label="anchor" href="#estimation-of-the-cate-score-with-catefit"></a>
</h3>
<p>If no internal validation is needed or the user has chosen the
scoring methods wanted, we can fit the PM methods directly to the entire
given dataset and get the CATE score and ATE results. This is done with
the function <code><a href="../reference/catefit.html">catefit()</a></code>.</p>
<p>In general, <code><a href="../reference/catefit.html">catefit()</a></code> has similar arguments as
<code><a href="../reference/catecv.html">catecv()</a></code>. The mandatory arguments are the same:
<code>response</code>, <code>data</code>, <code>score.method</code>,
<code>cate.model</code>, and <code>ps.model</code> and they must be
specified by the user. The user can also specify the non-mandatory
arguments to fit with the data and problem at hand. Please see the
function description of catefitsurv (<code><a href="../reference/catefitsurv.html">?catefitsurv</a></code>) for
details. Because there is no internal validation, <code><a href="../reference/catefit.html">catefit()</a></code>
does not have the <code>cv.n</code>, <code>train.prop</code>,
<code>abc</code>, and <code>prop.multi</code> arguments. This is the
main distinction between these 2 output functions. We specified the
mandatory and non-mandatory arguments the same way as
<code><a href="../reference/catecv.html">catecv()</a></code> in the example for demonstration purpose.</p>
<p>If you run into errors or warnings with your data, it might be
helpful to go over the descriptions to see if you need to alter the
default values. In this toy example, we keep the default values of the
remaining arguments.</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Sys.time.html" class="external-link">Sys.time</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">tau0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html" class="external-link">with</a></span><span class="op">(</span><span class="va">survivalExample</span>,</span>
<span>             <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html" class="external-link">min</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/quantile.html" class="external-link">quantile</a></span><span class="op">(</span><span class="va">y</span><span class="op">[</span><span class="va">trt</span> <span class="op">==</span> <span class="st">"drug1"</span><span class="op">]</span>, <span class="fl">0.95</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html" class="external-link">quantile</a></span><span class="op">(</span><span class="va">y</span><span class="op">[</span><span class="va">trt</span> <span class="op">==</span> <span class="st">"drug0"</span><span class="op">]</span>, <span class="fl">0.95</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">output_catefit</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/catefit.html">catefit</a></span><span class="op">(</span>response <span class="op">=</span> <span class="st">"survival"</span>,</span>
<span>                          data <span class="op">=</span> <span class="va">survivalExample</span>,</span>
<span>                          score.method <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span> <span class="st">"randomForest"</span>, <span class="st">"contrastReg"</span><span class="op">)</span>,</span>
<span>                          cate.model <span class="op">=</span> <span class="fu">survival</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html" class="external-link">Surv</a></span><span class="op">(</span><span class="va">y</span>, <span class="va">d</span><span class="op">)</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">female</span> </span>
<span>                                       <span class="op">+</span> <span class="va">previous_cost</span> <span class="op">+</span> <span class="va">previous_number_relapses</span>,</span>
<span>                          ps.model <span class="op">=</span> <span class="va">trt</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">previous_treatment</span>,</span>
<span>                          initial.predictor.method <span class="op">=</span> <span class="st">"logistic"</span>,</span>
<span>                          ipcw.model <span class="op">=</span> <span class="cn">NULL</span>,</span>
<span>                          followup.time <span class="op">=</span> <span class="cn">NULL</span>,</span>
<span>                          tau0 <span class="op">=</span> <span class="va">tau0</span>, </span>
<span>                          higher.y <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>                          surv.min <span class="op">=</span> <span class="fl">0.025</span>,</span>
<span>                          seed <span class="op">=</span> <span class="fl">999</span>,</span>
<span>                          plot.gbmperf <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<pre><code><span><span class="co">## Warning in data.preproc.surv(fun = "catefit", cate.model = cate.model, ps.model = ps.model, : Variable trt was recoded to 0/1 with drug0-&gt;0 and drug1-&gt;1.</span></span></code></pre>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Sys.time.html" class="external-link">Sys.time</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">t1</span> <span class="op">-</span> <span class="va">t0</span></span></code></pre></div>
<pre><code><span><span class="co">## Time difference of 9.084764 secs</span></span></code></pre>
<p>Despite the similar arguments, the outputs of <code><a href="../reference/catefit.html">catefit()</a></code>
and <code><a href="../reference/catecv.html">catecv()</a></code> differ. Each method specified in
<code>score.method</code> has the following sets of results in
<code><a href="../reference/catefit.html">catefit()</a></code>:</p>
<ol style="list-style-type: decimal">
<li>
<code>score</code> contains the log-transformed estimated CATE
scores for each subject. The CATE score is a linear combination of the
variables specified in the <code>cate.model</code> argument. Same as the
outcome, lower CATE scores are more desirable if <code>higher.y</code> =
FALSE and vice versa. In our example, the survival outcome is time to
first relapse, which is a negative event, so higher values indicate
later onset of the first relapse. Hence, we specify
<code>higher.y</code> = TRUE in the example. Each subject has 1 CATE
score so the length of this output is 4,000 for our toy example. Below
we show the CATE scores estimated with contrast regression for the first
6 subjects in the data.</li>
</ol>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/length.html" class="external-link">length</a></span><span class="op">(</span><span class="va">output_catefit</span><span class="op">$</span><span class="va">score.contrastReg</span><span class="op">)</span></span></code></pre></div>
<pre><code><span><span class="co">## [1] 4000</span></span></code></pre>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html" class="external-link">head</a></span><span class="op">(</span><span class="va">output_catefit</span><span class="op">$</span><span class="va">score.contrastReg</span><span class="op">)</span></span></code></pre></div>
<pre><code><span><span class="co">## [1]  5.3273340  1.1661594  3.4869179  4.0157912 -0.8475816  2.4217492</span></span></code></pre>
<ol start="2" style="list-style-type: decimal">
<li>
<code>coefficients</code> contains the estimated coefficients of the
CATE score for each scoring method. It is a data frame of the covariates
(including intercept) as rows and scoring methods as columns. In our toy
example, there are 4 covariates in the <code>cate.model</code>, plus the
intercept, so there are 5 rows of estimated coefficients within each
column. Boosting method does not estimate coefficients (it directly
predicts the score) so they do not have coefficient results here.</li>
</ol>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">output_catefit</span><span class="op">$</span><span class="va">coefficients</span></span></code></pre></div>
<pre><code><span><span class="co">##                          contrastReg</span></span>
<span><span class="co">## (Intercept)                0.2526763</span></span>
<span><span class="co">## age                       -0.1912056</span></span>
<span><span class="co">## female                     0.1359512</span></span>
<span><span class="co">## previous_cost              0.5629853</span></span>
<span><span class="co">## previous_number_relapses   0.3703522</span></span></code></pre>
<p>We can define the estimated CATE scores for contrast regression like
shown below. The user can use this information to study the influence of
each covariate. <span class="math display">\[
\begin{aligned}
\widehat{CATE} = 0.25 &amp; - 0.19 \times \text{age} \\
&amp; + 0.15 \times \text{female (vs male)} \\
&amp; + 0.56 \times \text{previous medical costs} \\
&amp; + 0.39 \times \text{previous number of relapses}
\end{aligned}
\]</span></p>
<ol start="3" style="list-style-type: decimal">
<li>
<code>ate</code> contains estimated ATEs by each nested subgroup of
high responders to drug 1 defined by <code>prop.cutoff</code>. The
subgroups are defined based on the estimated CATE scores with the
specified scoring method. In this example, we show the estimated ATEs of
subgroups identified by CATE scores of the contrast regression. For
example, the estimated ATE for the subgroup of subjects constructed
based on the 50% (“prop0.5”) lowest CATE scores estimated from the
contrast regression is 0.41.</li>
</ol>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">output_catefit</span><span class="op">$</span><span class="va">ate.contrastReg</span></span></code></pre></div>
<pre><code><span><span class="co">##   prop0.5   prop0.6   prop0.7   prop0.8   prop0.9     prop1 </span></span>
<span><span class="co">## 0.4105682 0.5114925 0.6269751 0.7800895 0.9145661 1.0726748</span></span></code></pre>
<p>You are encouraged to summarize and visualize the outputs in
whichever way that fits their particular situation outside the package’s
functions. For example, it is possible to plot the densities of all CATE
scores with <code>ggplot</code>. There are some subjects with extremely
high estimated CATE scores but most of the samples fall between -10 and
10.</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dataplot</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html" class="external-link">data.frame</a></span><span class="op">(</span>score <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html" class="external-link">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html" class="external-link">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"Random Forest"</span>, <span class="st">"Contrast regression"</span><span class="op">)</span>, </span>
<span>                                          each <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html" class="external-link">length</a></span><span class="op">(</span><span class="va">output_catefit</span><span class="op">$</span><span class="va">score.randomForest</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>, </span>
<span>                       value <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="va">output_catefit</span><span class="op">$</span><span class="va">score.randomForest</span>,<span class="va">output_catefit</span><span class="op">$</span><span class="va">score.contrastReg</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">dataplot</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html" class="external-link">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html" class="external-link">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html" class="external-link">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">value</span>, fill <span class="op">=</span> <span class="va">score</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_density.html" class="external-link">geom_density</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html" class="external-link">theme_classic</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html" class="external-link">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Estimated CATE score"</span>, y <span class="op">=</span> <span class="st">"Density"</span>, fill <span class="op">=</span> <span class="st">"Method"</span><span class="op">)</span></span></code></pre></div>
<pre><code><span><span class="co">## Warning: Removed 5 rows containing non-finite values (stat_density).</span></span></code></pre>
<p><img src="Survival-examples_files/figure-html/plot_score-1.png" width="700" style="display: block; margin: auto;"></p>
</div>
<div class="section level3">
<h3 id="estimation-of-the-ate-with-atefit">Estimation of the ATE with <code>atefit()</code><a class="anchor" aria-label="anchor" href="#estimation-of-the-ate-with-atefit"></a>
</h3>
<p>Beyond exploring treatment effect heterogeneity,
<code><a href="../reference/atefit.html">atefit()</a></code> allows estimating the ATE in terms of RMTL and HR.
The RMTL estimator is doubly robust, meaning that the estimator is
consistent if the PS model (argument <code>ps.model</code>) or the
outcome model (argument <code>cate.model</code>) or both are correctly
specified. The estimator also depends on the estimation of IPCW. The HR
estimator is based on a Cox regression model. The function also provides
standard error, confidence intervals, and p-values based on
bootstrap.</p>
<p>The mandatory arguments are: <code>response</code>,
<code>data</code>, <code>cate.model</code>, and <code>ps.model</code>.
Those arguments have the same definitions as in <code><a href="../reference/catecv.html">catecv()</a></code>
and <code><a href="../reference/catefit.html">catefit()</a></code>.</p>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">output_atefit</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/atefit.html">atefit</a></span><span class="op">(</span>response <span class="op">=</span> <span class="st">"survival"</span>,</span>
<span>                        data <span class="op">=</span> <span class="va">survivalExample</span>,</span>
<span>                        cate.model <span class="op">=</span> <span class="fu">survival</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html" class="external-link">Surv</a></span><span class="op">(</span><span class="va">y</span>, <span class="va">d</span><span class="op">)</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">female</span> <span class="op">+</span> <span class="va">previous_cost</span> <span class="op">+</span>                                                   <span class="va">previous_number_relapses</span>,</span>
<span>                        ps.model <span class="op">=</span> <span class="va">trt</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">previous_treatment</span>,</span>
<span>                        ps.method <span class="op">=</span> <span class="st">"glm"</span>,  </span>
<span>                        ipcw.model <span class="op">=</span> <span class="cn">NULL</span>,</span>
<span>                        ipcw.method <span class="op">=</span> <span class="st">"breslow"</span>,</span>
<span>                        minPS <span class="op">=</span> <span class="fl">0.01</span>, </span>
<span>                        maxPS <span class="op">=</span> <span class="fl">0.99</span>,</span>
<span>                        followup.time <span class="op">=</span> <span class="cn">NULL</span>,</span>
<span>                        tau0 <span class="op">=</span> <span class="va">tau0</span>,</span>
<span>                        surv.min <span class="op">=</span> <span class="fl">0.025</span>,</span>
<span>                        n.boot <span class="op">=</span> <span class="fl">50</span>,</span>
<span>                        seed <span class="op">=</span> <span class="fl">999</span>,</span>
<span>                        verbose <span class="op">=</span> <span class="fl">0</span><span class="op">)</span></span></code></pre></div>
<pre><code><span><span class="co">## Warning in data.preproc.surv(fun = "drinf", cate.model = cate.model, ps.model = ps.model, : Variable trt was recoded to 0/1 with drug0-&gt;0 and drug1-&gt;1.</span></span></code></pre>
<p>When <code>verbose</code> = 1, the function outputs a progress bar in
the console.</p>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">output_atefit</span></span></code></pre></div>
<pre><code><span><span class="co">## Average treatment effect:</span></span>
<span><span class="co">## </span></span>
<span><span class="co">##                   estimate         SE    CI.lower  CI.upper     pvalue</span></span>
<span><span class="co">## log.rmtl.ratio   0.0701553 0.03206484 0.007309376 0.1330012 0.02867542</span></span>
<span><span class="co">## log.hazard.ratio 2.7133243 0.20897752 2.303735883 3.1229127 0.00000000</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## Estimated RMST:</span></span>
<span><span class="co">## </span></span>
<span><span class="co">##       estimate       SE CI.lower CI.upper pvalue</span></span>
<span><span class="co">## rmst1 172.8609 6.271374 160.5692 185.1526      0</span></span>
<span><span class="co">## rmst0 196.5603 7.753894 181.3629 211.7576      0</span></span></code></pre>
<pre><code><span><span class="co">## Warning in print.atefit(x): Variable trt was recoded to 0/1 with drug0-&gt;0 and drug1-&gt;1.</span></span></code></pre>
<p>The output of <code><a href="../reference/atefit.html">atefit()</a></code> shows the point estimate,
standard error (“SE”), lower (“CI.lower”) and upper (“CI.upper”) bound
of the 95% confidence interval, and the p-value (“pvalue”) for 4
estimands:</p>
<ul>
<li><p>the restricted mean survival time under drug 1
(<code>$rmst1</code>)</p></li>
<li><p>the restricted mean survival time under drug 0
(<code>$rmst0</code>)</p></li>
<li><p>the log RMTL ratio (<code>$log.rmtl.ratio</code>), which is the
log of the ratio of <code>tau0</code> - <code>$rmst1</code> divided by
<code>tau0</code> - <code>$rmst0</code></p></li>
<li><p>the log HR (<code>$log.hazard.ratio</code>).</p></li>
</ul>
<p>For example, the log RMTL ratio of 0.07 and the 95% confidence
interval of (0.01, 0.13) are displayed in the output. The user can
retrieve the RMTL ratio to facilitate the interpretation:</p>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">rmtl.ratio</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html" class="external-link">exp</a></span><span class="op">(</span><span class="va">output_atefit</span><span class="op">$</span><span class="va">log.rmtl.ratio</span><span class="op">$</span><span class="va">estimate</span><span class="op">)</span></span>
<span><span class="va">rmtl.ratio</span></span></code></pre></div>
<pre><code><span><span class="co">## [1] 1.072675</span></span></code></pre>
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">CI.rmtl.ratio</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html" class="external-link">exp</a></span><span class="op">(</span><span class="va">output_atefit</span><span class="op">$</span><span class="va">log.rmtl.ratio</span><span class="op">$</span><span class="va">estimate</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html" class="external-link">qnorm</a></span><span class="op">(</span><span class="fl">0.975</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">sqrt</a></span><span class="op">(</span><span class="va">output_atefit</span><span class="op">$</span><span class="va">log.rmtl.ratio</span><span class="op">$</span><span class="va">SE</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">CI.rmtl.ratio</span></span></code></pre></div>
<pre><code><span><span class="co">## [1] 0.7551728 1.5236661</span></span></code></pre>
<p>The RMTL ratio of 1.07 along with the 95% confidence interval of
(0.76, 1.52) suggest that drug 1 is superior to drug 0 because the ratio
is significantly greater than 1.</p>
<p>The output of <code><a href="../reference/atefit.html">atefit()</a></code> is expressed in terms of
treatment 0 vs 1, where the RMTL and hazard ratios are expressed as the
ratio of the treatment coded as 1 over the treatment coded as 0. If the
treatment variable is not coded as 0/1 in the data set, the function
returns a warning <code>output_atefit$warning</code> which indicates
what key was used to recode the treatment variable into a 0/1
variable.</p>
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">output_atefit</span><span class="op">$</span><span class="va">warning</span></span></code></pre></div>
<pre><code><span><span class="co">## [1] "Variable trt was recoded to 0/1 with drug0-&gt;0 and drug1-&gt;1.\n"</span></span></code></pre>
<p>Using <code>plot(output_atefit)</code>, a histograms is generated of
the point estimates across the <code>n.boot</code> bootstrap iterations
for 4 estimands (<code>rmst1</code>, <code>rmst0</code>,
<code>log.rmtl.ratio</code>, <code>log.hazard.ratio</code>). A red
vertical line is added to each histogram with the mean of the bootstrap
estimates.</p>
<div class="figure">
<img src="atefit_bootstrap.png" alt=""><p class="caption">Figure. Histograms of bootstrap estimators for 4
estimands after 500 bootstrap iterations</p>
</div>
</div>
</div>
<div class="section level2">
<h2 id="other-precmed-vignettes-in-this-serie">Other <code>precmed</code> vignettes in this serie<a class="anchor" aria-label="anchor" href="#other-precmed-vignettes-in-this-serie"></a>
</h2>
<p><a href="General-introduction.html">1. General introduction</a><br><a href="Count-examples.html">2. Examples for count outcome</a><br><a href="Survival-examples.html">3. Examples for survival
outcome</a><br><a href="Additional-examples.html">4. Additional examples</a><br><a href="Theoretical-details.html">5. Theoretical details</a></p>
</div>
  </main><aside class="col-md-3"><nav id="toc"><h2>On this page</h2>
    </nav></aside>
</div>



    <footer><div class="pkgdown-footer-left">
  <p></p>
<p>Developed by Lu Tian, Xiaotong Jiang, Gabrielle Simoneau, Thomas Debray.</p>
</div>

<div class="pkgdown-footer-right">
  <p></p>
<p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.0.6.</p>
</div>

    </footer>
</div>

  

  

  </body>
</html>
